### ISSUE TITLE
Will you have any plan to release model weights?

### ISSUE THREAD

**Issue by MaoAYD** [CrossmodalGroup/DynamicVectorQuantization#2]
Trainig the model with limited GPU resource is not easy. if you can, it very thanks.

**Comment by Corleone-Huang** [comment]
> Trainig the model with limited GPU resource is not easy. if you can, it very thanks.

Hi, we provide the pre-trained DQ-VAE. Please refer to the updated ReadME. We will provide more pre-trained models in the further if possible.

**Comment by MaoAYD** [comment]
really thanks
